#!/usr/bin/env python3
"""Generate LaTeX/PDF reports from independently verified SSA results."""

from __future__ import annotations

import subprocess
from pathlib import Path

import sympy as sp

from elspice_mna.converters import SPECS, analyze_converter

ROOT = Path(__file__).resolve().parents[1]
ARTIFACTS = ROOT / "artifacts"

PHASE_LAWS = {
    "buck": (
        "ON: & L\\dot i_L=v_g-v_o, & C\\dot v_o=i_L-v_o/R,\\\\",
        "OFF: & L\\dot i_L=-v_o, & C\\dot v_o=i_L-v_o/R.",
    ),
    "boost": (
        "ON: & L\\dot i_L=v_g, & C\\dot v_o=-v_o/R,\\\\",
        "OFF: & L\\dot i_L=v_g-v_o, & C\\dot v_o=i_L-v_o/R.",
    ),
    "buck_boost": (
        "ON: & L\\dot i_L=v_g, & C\\dot v_o=-v_o/R,\\\\",
        "OFF: & L\\dot i_L=v_o, & C\\dot v_o=-i_L-v_o/R.",
    ),
}


def tex_report(key: str, analysis: dict) -> str:
    latex = sp.latex
    title = analysis["spec"].title
    phase_on, phase_off = PHASE_LAWS[key]
    verification = "\n".join(
        f"\\item \\textbf{{PASS}} --- {item}." for item in analysis["verification"]
    )
    return rf"""\documentclass[11pt]{{article}}
\usepackage[a4paper,margin=20mm]{{geometry}}
\usepackage{{amsmath,amssymb,booktabs,array,microtype}}
\usepackage[T1]{{fontenc}}
\title{{{title}: Verified State-Space Averaging}}
\author{{Generated by elspice-mna}}
\date{{1 August 2026}}
\begin{{document}}
\maketitle

\section*{{Assumptions and notation}}
The converter is ideal, operates in continuous-conduction mode at fixed
switching frequency, and drives a resistive load $R$. The state vector is
$x=[i_L\;v_o]^T$, $D$ is the ON duty ratio, and $D'=1-D$. For the inverting
buck--boost, $v_o$ is the physical negative output voltage.

\section*{{Independent hand derivation}}
Kirchhoff's laws give
\begin{{align}}
{phase_on}
{phase_off}
\end{{align}}
These laws were entered independently of the MNA matrices and are used as the
verification oracle.

\section*{{Switching topology models from Rust MNA}}
\begin{{align}}
\dot x &= A_{{on}}x+B_{{g,on}}v_g,
&A_{{on}}&={latex(analysis['A_on'])},
&B_{{g,on}}&={latex(analysis['Bg_on'])},\\
\dot x &= A_{{off}}x+B_{{g,off}}v_g,
&A_{{off}}&={latex(analysis['A_off'])},
&B_{{g,off}}&={latex(analysis['Bg_off'])}.
\end{{align}}

\section*{{Input-to-output state-space representation}}
State-space averaging gives
\begin{{equation}}
\dot{{\hat x}}=A\hat x+B_g\hat v_g,\qquad
\hat v_o=C_y\hat x,\qquad C_y=\begin{{bmatrix}}0&1\end{{bmatrix}},
\end{{equation}}
where
\begin{{equation}}
A={latex(analysis['A'])},\qquad B_g={latex(analysis['Bg'])}.
\end{{equation}}
The corresponding transfer function is
\begin{{equation}}
G_{{vg}}(s)=\frac{{\hat v_o(s)}}{{\hat v_g(s)}}
=C_y(sI-A)^{{-1}}B_g={latex(analysis['H_vg'])}.
\end{{equation}}

\section*{{Control-to-output state-space representation}}
The steady operating point is
\begin{{equation}}
X=-A^{{-1}}B_gV_g={latex(analysis['X_dc'])}.
\end{{equation}}
Linearization with respect to duty gives
\begin{{equation}}
B_d=(A_{{on}}-A_{{off}})X+(B_{{g,on}}-B_{{g,off}})V_g
={latex(analysis['Bd'])}.
\end{{equation}}
Therefore
\begin{{equation}}
\dot{{\hat x}}=A\hat x+B_d\hat d,\qquad
\hat v_o=C_y\hat x,
\end{{equation}}
and
\begin{{equation}}
G_{{vd}}(s)=\frac{{\hat v_o(s)}}{{\hat d(s)}}
=C_y(sI-A)^{{-1}}B_d={latex(analysis['H_vd'])}.
\end{{equation}}

\section*{{Verification}}
\begin{{itemize}}
{verification}
\end{{itemize}}
All symbolic differences simplify exactly to zero. As a second check, the
Rust numeric reducer and the SymPy descriptor reducer agree at
$L=100\,\mu\mathrm{{H}}$, $C=220\,\mu\mathrm{{F}}$, and $R=12\,\Omega$.

\end{{document}}
"""


def main() -> None:
    ARTIFACTS.mkdir(parents=True, exist_ok=True)
    for key in SPECS:
        analysis = analyze_converter(key)
        stem = f"{key}_converter_state_space"
        tex_path = ARTIFACTS / f"{stem}.tex"
        tex_path.write_text(tex_report(key, analysis), encoding="utf-8")
        subprocess.run(
            [
                "pdflatex",
                "-interaction=nonstopmode",
                "-halt-on-error",
                "-output-directory",
                str(ARTIFACTS),
                str(tex_path),
            ],
            check=True,
            cwd=ROOT,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
        )
        print(f"generated artifacts/{stem}.pdf")


if __name__ == "__main__":
    main()
